# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Slider"
  description: "Main page banner block"
  icon: "title"
  tags:

# Defines the structure of this component, as well as the default values
blueprint:
  preheading: "Prepare for a new future"
  heading: "Our work is a <br>presentation of our <br>capabilities."
  link:
    text: "Get started"
    url: "#"

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
