# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Nav
  description: Site navigation
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  styles:
    min_height:
    padding:
    bg_color:
    logo:
      max_width:
      margin:
    nav_links:
      text_color:
      text_size:
      margin:
    hamburger:
      margin:
      width:
      color:
  content:
    logo_src: ""
    links:
      - name: ""
        url: ""

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  content:
    logo_src: "http://placekitten.com/40/40"
    links:
      - name: Features
        url: /
      - name: Blog
        url: /
      - name: Documentation
        url: /
      - name: Contact
        url: /

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  logo_src:
    type: image
  max_width:
    type: range
    options:
      step: 0.1
      max: 10
      min: 0
  width:
    type: range
    options:
      step: 0.1
      max: 10
      min: 0
  min_height:
    type: range
    options:
      step: 0.1
      max: 10
      min: 0
  bg_color:
    type: color
    options:
      format: rgba
      alpha: true
  color:
    type: color
    options:
      format: rgba
      alpha: true
  text_size:
    type: range
    options:
      step: 0.1
      max: 10
      min: 0
  padding:
    type: range
    options:
      step: 0.01
      max: 8
      min: 0
  margin:
    type: range
    options:
      step: 0.01
      max: 8
      min: 0
  text_color:
    type: color
    options:
      format: rgba
      alpha: true
