# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Nav
  description: Site navigation
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  styles:
    min_height:
    bg_color:
    logo_max_width:
    text_color:
  content:
    logo: ""
    links:
      - name: ""
        url: ""

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  content:
    logo: "http://placekitten.com/40/40"
    links:
      - name: Features
        url: /
      - name: Blog
        url: /
      - name: Documentation
        url: /
      - name: Contact
        url: /

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  logo:
    type: image
  logo_min_width:
    type: range
    options:
      step: 0.1
      max: 10
      min: 0
  min_height:
    type: range
    options:
      step: 0.1
      max: 10
      min: 0
  bg_color:
    type: color
    options:
      format: rgba
      alpha: true
  text_color:
    type: color
    options:
      format: rgba
      alpha: true
