# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "intro"
  description: "Overview section"
  icon: "receipt"
  tags:

# Defines the structure of this component, as well as the default values
blueprint:
  styles:
    bg_color:
    text_max_width:
    heading:
      color:
      font_size:
        min:
        view_width:
        max:
    tagline:
      color: 
      font_size:
        min:
        view_width:
        max:
    image:
      image_src:
      top:
      right:
      opacity:
      width:
        min:
        view_width:
        max:
      border_radius:
  content:
    heading: Brash Landscapes
    tagline: caring for dunedin gardens
    image: "https://placekitten.com/300/300"

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  image_src:
    type: image
  bg_color:
    type: color
    options:
      format: rgba
      alpha: true
  color:
    type: color
    options:
      format: rgba
      alpha: true
  min:
    type: range
    options:
      step: 1
      max: 100
      min: 0
  view_width:
    type: range
    options:
      step: .1
      max: 100
      min: 0
  max:
    type: range
    options:
      step: 1
      max: 1200
      min: 0
  top:
    type: range
    options:
      step: 1
      max: 500
      min: 0
  right:
    type: range
    options:
      step: 1
      max: 500
      min: 0
  opacity:
    type: range
    options:
      step: 1
      max: 100
      min: 0
  border_radius:
    type: range
    options:
      step: 1
      max: 50
      min: 0
  text_max_width:
    type: range
    options:
      step: 1
      max: 100
      min: 0