# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Intro"
  description: "Overview section"
  icon: "receipt"
  tags:

# Defines the structure of this component, as well as the default values
blueprint:
  preheading: "We are creative & expert people"
  heading: "We work with business & provide solution to client with their business problem"
  sections:
    - heading: "Modern & Responsive design"
      text: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odit, ducimus."
    - heading2: "Awarded licensed company"
      text2: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odit, ducimus."

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
