# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Color-block"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  text: "Our Services"
  list:
    - item: "General garden maintenance"
    - item: "Pruning services"
    - item: "Lawn care"

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
